### ISSUE TITLE
OAuth connectivity?

### ISSUE THREAD

**Issue by AshBT** [mbrenig/SheetSync#8]
starting to have this issue:
ClientLoginFailed: Server responded to ClientLogin request: 404, https://developers.google.com/accounts/docs/AuthForInstalledApps

It's because we need to connect via OAuth not login/password.

**Comment by mbrenig** [comment]
Thanks. It's something we saw too, you can try the experimental "oauth" branch I just pushed, but it's not fully tested.

The constructor for the "Sheet" object changes in two ways:
* It takes an [OAuth2Credentials](https://developers.google.com/identity/protocols/OAuth2#installed) object instead of username/password
* "sheet_name" parameter is renamed to "worksheet_name" to be more specific.

Have also added a function (ia_credentials_helper) to make testing command line applications (that use an [installed application](https://developers.google.com/identity/protocols/OAuth2#installed) client key) a bit easier.

**Comment by AshBT** [comment]
Thanks for making the update

I noticed a small bug on line 1048:
logger.debug("Batching write of %s", value[:50])

It throws errors when you don't have an indexable value.  I ended up
commenting it out on my end.

Cheers,
ᐧ

On Thu, May 28, 2015 at 8:37 AM, Mark <notifications@github.com> wrote:

> Thanks. It's something we saw too, you can try the experimental "oauth"
> branch I just pushed, but it's not fully tested.
>
> The constructor for the "Sheet" object changes in two ways:
>
>    - It takes an OAuth2Credentials
>    <https://developers.google.com/identity/protocols/OAuth2#installed>
>    object instead of username/password
>    - "sheet_name" parameter is renamed to "worksheet_name" to be more
>    specific.
>
> Have also added a function (ia_credentials_helper) to make testing command
> line applications (that use an installed application
> <https://developers.google.com/identity/protocols/OAuth2#installed>
> client key) a bit easier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbrenig/SheetSync/issues/8#issuecomment-106297007>.
>



-- 
Ashley Beattie

**Comment by mjg10** [comment]
Sorry for the noob question.  Is there a way to install OAuth via pip or command line python on my local machine?

Or, do I need to learn either some other semi automated or manual procedure for grabbing the new code?

thanks

**Comment by mjg10** [comment]
i attempted to solve this myself by downloading the zip of the oauth branch and simply overwriting the __init__ and version files in my C:\Python27\Lib\site-packages\sheetsync directory but that doesnt seem to do it.

**Comment by mjg10** [comment]
i actually managed to get a lot further along after installing googles new oauth module i think, which got me a bunch further.

i think i also installed nose, google api python client, gspread, etc.  but now i get...

INFO:__main__:Error:<type 'exceptions.TypeError'>//__init__() got an unexpected keyword argument 'username'
INFO:__main__:Trace:[('C:\\Users\\mgavriel\\Workspaces\\somethingUnique\\firstProject\\speakeasy_subsequent_query_sprint\\OneTick\\pyqt_example.py', 229, 'main', 'main_window = AppWindow(feed_dict=feeds, signalContainer=signalContainer, dataManager=dataManager, time_zone=time_zone, timeout=0)'), ('C:\\Users\\mgavriel\\Workspaces\\somethingUnique\\firstProject\\speakeasy_subsequent_query_sprint\\OneTick\\pyqt_example.py', 94, '__init__', 'self.dataManager=dataManager(self.signalDict)'), ('C:\\Users\\mgavriel\\Workspaces\\somethingUnique\\firstProject\\speakeasy_subsequent_query_sprint\\OneTick\\pyqt_example_data_management.py', 210, '__init__', 'sheet_name="Sheet1")')]
INFO:__main__:exiting program due to exception

-- is there a 'new' way to enter username that i dont know of?

**Comment by mjg10** [comment]
sorry for the 10 messages.  i managed to find some pointers, but still dont know what to do.

i see you've specified:

        Args:
          credentials (OAuth2Credentials): Credentials object returned by the
            google authorization server. Described in detail in this article:
            https://developers.google.com/api-client-library/python/guide/aaa_oauth
            For testing and development consider using the helper function:
                sheetsync.ia_credentials_helper()

but im not sure either how to set up the credentials (i can ask a sys admin perhaps?), nor how to use the helper func ... all i 'know' are my google username / pwd in the normal sense ...

**Comment by wieclaw** [comment]
Hi,
I'm trying to use sheetsync with OAuth2Credentials (from oauth branch).

I have created a service account in Google Aps (https://developers.google.com/identity/protocols/OAuth2ServiceAccount) then I have enabled Drive API (in console.developers.google.com) and finally I have registered https://docs.google.com/feeds/, https://spreadsheets.google.com/feeds/ and https://www.googleapis.com/auth/drive scopes for created service account (in admin.google.com "Manage API client access").

I create credentials object (for use with sheetsync) using 'https://spreadsheets.google.com/feeds/' scope.

When I try to open spreadsheet I get:
googleapiclient.errors.HttpError: &lt;HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx?alt=json returned "Insufficient Permission"&gt;

Any ideas what am I missing?
Have anyone accessed a spreadsheet using sheetsync with OAuth2?

**Comment by crosbyja** [comment]
Had the same issue, two things are needed:
1)An additional scope of https://www.googleapis.com/auth/drive
2)Make sure you have given sharing permissions on the sheet to the client email in your oauth credentials, that's the xxxxxx@developer.gserviceaccount.com

**Comment by wieclaw** [comment]
Thank you very much!
It was the scope issue.

**Comment by mbrenig** [comment]
The OAuth approach is now in the default branch, and documented here: http://sheetsync.readthedocs.org/en/latest/getting_started.html#setting-up-oauth-2-0-access

So I'm closing this. Thanks.
